### PR TITLE
Added user profiles + new styling, fixed post-author relation

### LINKED ISSUE #12: Profiles with feeds
Users should be able to visit other user profiles by clicking on the username field on any post. Profiles should contain information about the user, as well as a feed of all their posts and re-posts. Possibly also sticky posts, but that's a feature for another day.

**Implementation**
A `/api/v1/posts/by-user/{username}` endpoint which takes a Pageable and returns all of the posts and reposts from that user. This information should be accessed and displayed on a new React page called `Profile.tsx`, which contains profile information and a `Feed.tsx` which takes this endpoint.

### PR DESCRIPTION
**Pull request by melleg**
Closes #12

### CODE REVIEW

File: backend/src/main/java/nl/itvitae/twitbook/post/Post.java [hunk 1]
```diff
@@ -1,9 +1,6 @@
 package nl.itvitae.twitbook.post;
 
-import jakarta.persistence.Entity;
-import jakarta.persistence.GeneratedValue;
-import jakarta.persistence.GenerationType;
-import jakarta.persistence.Id;
+import jakarta.persistence.*;
```
Comment (mio-xenoblade) [inline backend/src/main/java/nl/itvitae/twitbook/post/Post.java]: Might not be preferred

File: backend/src/main/java/nl/itvitae/twitbook/post/PostController.java [hunk 2]
```diff
@@ -44,6 +44,15 @@ public ResponseEntity<?> getById(@PathVariable Long id) {
     return new ResponseEntity<>(new PostDTO(post.get()), HttpStatus.OK);
   }
 
+  @GetMapping("by-username/{username}")
+  public ResponseEntity<?> getByUsername(@PathVariable String username) {
+    Optional<User> user = userRepository.findByUsername(username);
```
Comment (mio-xenoblade) [inline backend/src/main/java/nl/itvitae/twitbook/post/PostController.java]: change to findByUsernameIgnoreCase

File: backend/src/main/java/nl/itvitae/twitbook/user/UserController.java [hunk 3]
```diff
@@ -21,4 +21,14 @@ public class UserController {
   public List<UserDTO> getAll() {
     return userRepository.findAll().stream().map(UserDTO::new).toList();
   }
+
+  @GetMapping("by-username/{username}")
+  public ResponseEntity<?> findByUsername(@PathVariable String username) {
+    Optional<User> user = userRepository.findByUsername(username);
```
Comment (mio-xenoblade) [inline backend/src/main/java/nl/itvitae/twitbook/user/UserController.java]: ignore case

File: backend/src/main/java/nl/itvitae/twitbook/user/UserRepository.java [hunk 4]
```diff
@@ -1,8 +1,9 @@
 package nl.itvitae.twitbook.user;
 
+import java.util.Optional;
 import java.util.UUID;
 import org.springframework.data.jpa.repository.JpaRepository;
 
 public interface UserRepository extends JpaRepository<User, UUID> {
-
+    public Optional<User> findByUsername(String username);
```
Comment (mio-xenoblade) [inline backend/src/main/java/nl/itvitae/twitbook/user/UserRepository.java]: ignore case

File: frontend/src/main.tsx [hunk 5]
```diff
@@ -15,18 +15,18 @@ const router = createBrowserRouter([
...
-      {
-        path: "posts",
-        element: <ViewPostsComponent />,
-      },
       {
         path: "login",
         element: <LoginComponent />,
       },
+      {
+        path: "profile/:id",
```
Comment (mio-xenoblade) [inline frontend/src/main.tsx]: rename to username

File: frontend/src/post/PostCard.tsx [hunk 6]
```diff
@@ -0,0 +1,44 @@
...
+
+interface PostCardProps {
+  post: Post;
+}
+
+const PostCard: React.FC<PostCardProps> = ({ post }) => {
+  return (
+    <div
+      className="p-4 glass rounded-lg flex flex-wrap items-start gap-2"
+      key={post.id}
```
Comment (mio-xenoblade) [inline frontend/src/post/PostCard.tsx]: remove key

File: frontend/src/profile/Profile.tsx [hunk 7]
```diff
@@ -0,0 +1,76 @@
+import { useEffect, useState } from "react";
+import User from "./user";
+import { useParams } from "react-router-dom";
+import { getUserByUsername } from "./user-service";
+import Feed from "../feed/Feed";
+import { getPostsByUser } from "../post/post-service";
+import { format } from "date-fns";
+
+function Profile() {
+  const { id } = useParams();
```
Comment (mio-xenoblade) [inline frontend/src/profile/Profile.tsx]: username

**Review by mio-xenoblade — CHANGES_REQUESTED** [review]

**Review by mio-xenoblade — APPROVED** [review]
